os: linux
language: node_js
node_js: 8.11.2

cache:
    directories: node_modules

before_script:
    - git lfs pull

env: ❤ = NodeJS Lint + Build + Generate
script:
    - yarn lint
    - yarn build
    - yarn generate
